{
 "title": "New dashboard Copy",
 "time": { "from": "2018-12-31T23:00:00.000Z", "to": "2021-01-09T23:00:00.000Z" },
 "panels": [
  {
   "title": "Meilleurs CA 2021",
   "type": "gauge",
   "description": "TOP 10 en chiffres d'affaire",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP(CONCAT(CONVERT(annee, CHAR), \":01:01\")) AS \"time\",\n  titre AS metric,\n  CA AS \"CA\"\nFROM donnees_finance\nWHERE\n  annee = 2021\nORDER BY CA DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Moins bons EBE 2021",
   "type": "gauge",
   "description": "TOP 10 inversé sur les excédents bruts d'exploitation",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP(CONCAT(CONVERT(annee, CHAR), \":01:01\")) AS \"time\",\n  titre AS metric,\n  EBE AS \"EBE\"\nFROM donnees_finance\nWHERE\n  annee = 2021\nORDER BY EBE ASC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Chiffres d'affaire 2019 à 2021",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  TIMESTAMP(CONCAT(CONVERT(annee, CHAR), \":01:01\")) AS \"time\",\n  titre AS metric,\n  CA\nFROM donnees_finance\nORDER BY CA DESC\nLIMIT 30"
    }
   ]
  }
 ]
}